[2023-11-08T14:50:55.837+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yaCIss.test manual__2023-11-08T14:50:53.517479+00:00 [queued]>
[2023-11-08T14:50:55.847+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yaCIss.test manual__2023-11-08T14:50:53.517479+00:00 [queued]>
[2023-11-08T14:50:55.847+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-08T14:50:55.861+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): test> on 2023-11-08 14:50:53.517479+00:00
[2023-11-08T14:50:55.867+0000] {standard_task_runner.py:57} INFO - Started process 636 to run task
[2023-11-08T14:50:55.870+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yaCIss', 'test', 'manual__2023-11-08T14:50:53.517479+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/data/yarabi.py', '--cfg-path', '/tmp/tmpwehto18l']
[2023-11-08T14:50:55.874+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask test
[2023-11-08T14:50:55.930+0000] {task_command.py:416} INFO - Running <TaskInstance: yaCIss.test manual__2023-11-08T14:50:53.517479+00:00 [running]> on host e1bfed7213dc
[2023-11-08T14:50:56.014+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yaCIss' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2023-11-08T14:50:53.517479+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-08T14:50:53.517479+00:00'
[2023-11-08T14:50:56.016+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-08T14:50:56.017+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl --keepalive-time 600 -o ${AIRFLOW_HOME}/data/valeurs_foncieres.txt https://static.data.gouv.fr/resources/demandesde-valeurs-foncieres/20231010-093059/valeursfoncieres-2022.txt']
[2023-11-08T14:50:56.029+0000] {subprocess.py:86} INFO - Output:
[2023-11-08T14:50:56.047+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-11-08T14:50:56.048+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-11-08T14:50:56.127+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file /opt/***/data/valeurs_foncieres.txt: No
[2023-11-08T14:50:56.129+0000] {subprocess.py:93} INFO - Warning: such file or directory
[2023-11-08T14:50:56.130+0000] {subprocess.py:93} INFO - 100   146  100   146    0     0   1848      0 --:--:-- --:--:-- --:--:--  1848
[2023-11-08T14:50:56.131+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2023-11-08T14:50:56.133+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2023-11-08T14:50:56.150+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2023-11-08T14:50:56.155+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=yaCIss, task_id=test, execution_date=20231108T145053, start_date=20231108T145055, end_date=20231108T145056
[2023-11-08T14:50:56.170+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task test (Bash command failed. The command returned a non-zero exit code 23.; 636)
[2023-11-08T14:50:56.205+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-08T14:50:56.226+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
