[2023-11-24T21:49:32.786+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet1.extract_transform_clean_load manual__2023-11-24T21:49:16.033161+00:00 [queued]>
[2023-11-24T21:49:32.801+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet1.extract_transform_clean_load manual__2023-11-24T21:49:16.033161+00:00 [queued]>
[2023-11-24T21:49:32.802+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-24T21:49:32.822+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_transform_clean_load> on 2023-11-24 21:49:16.033161+00:00
[2023-11-24T21:49:32.830+0000] {standard_task_runner.py:57} INFO - Started process 5424 to run task
[2023-11-24T21:49:32.834+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet1', 'extract_transform_clean_load', 'manual__2023-11-24T21:49:16.033161+00:00', '--job-id', '1139', '--raw', '--subdir', 'DAGS_FOLDER/Projet.py', '--cfg-path', '/tmp/tmpofrptzky']
[2023-11-24T21:49:32.836+0000] {standard_task_runner.py:85} INFO - Job 1139: Subtask extract_transform_clean_load
[2023-11-24T21:49:32.890+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet1.extract_transform_clean_load manual__2023-11-24T21:49:16.033161+00:00 [running]> on host b36ebcee5948
[2023-11-24T21:49:32.976+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='filali.dia18@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet1' AIRFLOW_CTX_TASK_ID='extract_transform_clean_load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T21:49:16.033161+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-24T21:49:16.033161+00:00'
[2023-11-24T21:49:33.211+0000] {warnings.py:109} WARNING - /opt/***/dags/Projet.py:35: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_urgences = pd.read_csv(csv_file_path_urgences, delimiter=';')

[2023-11-24T21:49:33.457+0000] {logging_mixin.py:151} INFO - ########################################################################
[2023-11-24T21:49:33.457+0000] {logging_mixin.py:151} INFO - #                                                                      #
[2023-11-24T21:49:33.458+0000] {logging_mixin.py:151} INFO - #   ce dessous est la visualisation du contenu de la table Urgences :  #
[2023-11-24T21:49:33.458+0000] {logging_mixin.py:151} INFO - #                                                                      #
[2023-11-24T21:49:33.459+0000] {logging_mixin.py:151} INFO - ########################################################################
[2023-11-24T21:49:33.495+0000] {logging_mixin.py:151} INFO -         dep date_de_passage  ...  nbre_acte_tot_h  nbre_acte_tot_f
0        01      2022-12-26  ...              0.0              0.0
1        01      2022-12-26  ...              0.0              0.0
2        01      2022-12-26  ...              0.0              0.0
3        01      2022-12-26  ...              0.0              0.0
4        01      2022-12-26  ...              0.0              0.0
...     ...             ...  ...              ...              ...
214216  976      2023-10-24  ...              0.0              0.0
214217  976      2023-10-24  ...              0.0              0.0
214218  976      2023-10-24  ...              0.0              0.0
214219  976      2023-10-24  ...              0.0              0.0
214220  976      2023-10-24  ...              0.0              0.0

[214221 rows x 18 columns]
[2023-11-24T21:49:33.499+0000] {logging_mixin.py:151} INFO - ########################################################################
[2023-11-24T21:49:33.500+0000] {logging_mixin.py:151} INFO - #                                                                      #
[2023-11-24T21:49:33.500+0000] {logging_mixin.py:151} INFO - #   ce dessous est la visualisation du contenu de la table Urgences :  #
[2023-11-24T21:49:33.501+0000] {logging_mixin.py:151} INFO - #                                                                      #
[2023-11-24T21:49:33.501+0000] {logging_mixin.py:151} INFO - ########################################################################
[2023-11-24T21:49:33.508+0000] {logging_mixin.py:151} INFO -     num_dep                 dep_name                 region_name
0        01                      Ain        Auvergne-Rhône-Alpes
1        02                    Aisne             Hauts-de-France
2        03                   Allier        Auvergne-Rhône-Alpes
3        04  Alpes-de-Haute-Provence  Provence-Alpes-Côte d'Azur
4        05             Hautes-Alpes  Provence-Alpes-Côte d'Azur
..      ...                      ...                         ...
96      971               Guadeloupe                  Guadeloupe
97      972               Martinique                  Martinique
98      973                   Guyane                      Guyane
99      974               La Réunion                  La Réunion
100     976                  Mayotte                     Mayotte

[101 rows x 3 columns]
[2023-11-24T21:49:33.512+0000] {logging_mixin.py:151} INFO - Index(['code_age', 'agess'], dtype='object')
[2023-11-24T21:49:33.512+0000] {logging_mixin.py:151} INFO - Une erreur s'est produite lors de l'extraction des données Age : 'DataFrame' object has no attribute 'append'
[2023-11-24T21:49:33.522+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-24T21:49:33.558+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-24T21:49:33.587+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-24T21:49:58.063+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-24T21:49:58.085+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2023-11-24T21:49:58.170+0000] {logging_mixin.py:151} INFO - Une erreur s'est produite : 's'
[2023-11-24T21:49:58.174+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-24T21:49:58.185+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Projet1, task_id=extract_transform_clean_load, execution_date=20231124T214916, start_date=20231124T214932, end_date=20231124T214958
[2023-11-24T21:49:58.219+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-24T21:49:58.239+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
