[2023-11-11T16:25:43.270+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ProjetETL.telechargement_fichier1 manual__2023-11-11T16:17:24.168779+00:00 [queued]>
[2023-11-11T16:25:43.281+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ProjetETL.telechargement_fichier1 manual__2023-11-11T16:17:24.168779+00:00 [queued]>
[2023-11-11T16:25:43.282+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-11T16:25:43.299+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): telechargement_fichier1> on 2023-11-11 16:17:24.168779+00:00
[2023-11-11T16:25:43.305+0000] {standard_task_runner.py:57} INFO - Started process 24424 to run task
[2023-11-11T16:25:43.310+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ProjetETL', 'telechargement_fichier1', 'manual__2023-11-11T16:17:24.168779+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/Projet.py', '--cfg-path', '/tmp/tmpptxenthg']
[2023-11-11T16:25:43.312+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask telechargement_fichier1
[2023-11-11T16:25:43.374+0000] {task_command.py:416} INFO - Running <TaskInstance: ProjetETL.telechargement_fichier1 manual__2023-11-11T16:17:24.168779+00:00 [running]> on host fb26c01043df
[2023-11-11T16:25:43.474+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ProjetETL' AIRFLOW_CTX_TASK_ID='telechargement_fichier1' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T16:17:24.168779+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-11T16:17:24.168779+00:00'
[2023-11-11T16:25:43.478+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-11T16:25:43.479+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl --keepalive-time 600 -o $AIRFLOW_HOME/data/code-tranches-dage-donnees-urgences.csv']
[2023-11-11T16:25:43.497+0000] {subprocess.py:86} INFO - Output:
[2023-11-11T16:25:43.507+0000] {subprocess.py:93} INFO - curl: no URL specified!
[2023-11-11T16:25:43.508+0000] {subprocess.py:93} INFO - curl: try 'curl --help' or 'curl --manual' for more information
[2023-11-11T16:25:43.508+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-11T16:25:43.520+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-11T16:25:43.524+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ProjetETL, task_id=telechargement_fichier1, execution_date=20231111T161724, start_date=20231111T162543, end_date=20231111T162543
[2023-11-11T16:25:43.537+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 60 for task telechargement_fichier1 (Bash command failed. The command returned a non-zero exit code 2.; 24424)
[2023-11-11T16:25:43.564+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-11T16:25:43.582+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
