[2023-11-11T14:08:16.561+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ProjetETL.telechargement_fichier1 scheduled__2023-11-10T14:07:47.058854+00:00 [queued]>
[2023-11-11T14:08:16.570+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ProjetETL.telechargement_fichier1 scheduled__2023-11-10T14:07:47.058854+00:00 [queued]>
[2023-11-11T14:08:16.570+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-11T14:08:16.585+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): telechargement_fichier1> on 2023-11-10 14:07:47.058854+00:00
[2023-11-11T14:08:16.593+0000] {standard_task_runner.py:57} INFO - Started process 22758 to run task
[2023-11-11T14:08:16.597+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ProjetETL', 'telechargement_fichier1', 'scheduled__2023-11-10T14:07:47.058854+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/Projet.py', '--cfg-path', '/tmp/tmp_8tgll2m']
[2023-11-11T14:08:16.598+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask telechargement_fichier1
[2023-11-11T14:08:16.659+0000] {task_command.py:416} INFO - Running <TaskInstance: ProjetETL.telechargement_fichier1 scheduled__2023-11-10T14:07:47.058854+00:00 [running]> on host fb26c01043df
[2023-11-11T14:08:16.844+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ProjetETL' AIRFLOW_CTX_TASK_ID='telechargement_fichier1' AIRFLOW_CTX_EXECUTION_DATE='2023-11-10T14:07:47.058854+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-10T14:07:47.058854+00:00'
[2023-11-11T14:08:16.870+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-11T14:08:16.874+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl --keepalive-time 600 -o $AIRFLOW_HOME/data/code-tranches-dage-donnees-urgences.csv']
[2023-11-11T14:08:16.906+0000] {subprocess.py:86} INFO - Output:
[2023-11-11T14:08:16.967+0000] {subprocess.py:93} INFO - curl: no URL specified!
[2023-11-11T14:08:16.968+0000] {subprocess.py:93} INFO - curl: try 'curl --help' or 'curl --manual' for more information
[2023-11-11T14:08:16.969+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-11T14:08:16.980+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-11T14:08:16.985+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ProjetETL, task_id=telechargement_fichier1, execution_date=20231110T140747, start_date=20231111T140816, end_date=20231111T140816
[2023-11-11T14:08:17.000+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 43 for task telechargement_fichier1 (Bash command failed. The command returned a non-zero exit code 2.; 22758)
[2023-11-11T14:08:17.014+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-11T14:08:17.095+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
